# version: '3.8'

# services:
#   mysql-db:
#     image: mysql:latest
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: Gangster@1Gang
#     ports:
#       - "3307:3306"
#     volumes:
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mounting the SQL script
#       - mysql_data:/var/lib/mysql
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 10s
#       retries: 5
#       start_period: 20s
#       timeout: 5s

#   java-app:
#     build: .
#     depends_on:
#       mysql-db:
#         condition: service_healthy  # Java app waits until MySQL is ready
#     ports:
#       - "5901:5901"  # VNC port
#       - "6080:6080"  # noVNC web access
#     environment:
#       DISPLAY: ":1"
#       DB_HOST: mysql-db  # Use the service name as the host
#       DB_PORT: 3306
#       DB_NAME: GameProject
#       DB_USER: root
#       DB_PASSWORD: Gangster@1Gang
#     volumes:
#       - /tmp/.X11-unix:/tmp/.X11-unix  # Enable GUI

# volumes:
#   mysql_data:



version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gangster@1Gang
      MYSQL_DATABASE: GameProject 
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s  # ✅ Increased for better stability
      timeout: 5s

  java-app:
    build: .
    depends_on:
      mysql-db:
        condition: service_healthy  # ✅ Java app will wait until MySQL is ready
    ports:
      - "5901:5901"  # VNC port
      - "6080:6080"  # noVNC web access
    environment:
      DISPLAY: ":1"
      DB_HOST: mysql-db  # ✅ Use service name (NOT localhost)
      DB_PORT: 3306
      DB_NAME: GameProject
      DB_USER: root
      DB_PASSWORD: Gangster@1Gang
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Enable GUI

volumes:
  mysql_data:
